### PR TITLE
build 1.1.0

### PR DESCRIPTION
**Pull request by basnijholt**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
I am building from GitHub because @pbrady didn't update [PyPI](https://pypi.org/project/fastcache/) (even though 1.1.0 was released 8 months ago), which is why the update bot didn't get triggered.

**Comment by synapticarbors** [comment]
Thanks for the PR. I'm going to close this in favor of #6, which is based off of pypi.

**Comment by basnijholt** [comment]
Great! Yeah, I've asked the author of `fastcache` to put it on PyPI :)

**Pull request closed without merging**
